knihaJizd/Models/Accidents.cs
namespace knihaJizd.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class Accidents
    {
        public int Id { get; set; }

        [DisplayName("Adresa nehody")]
        public string AccidentAddress { get; set; }

        [DisplayName("Čas nehody")]
        public DateTime? AccidentTime { get; set; }

        [DisplayName("Jméno druhého řidiče")]
        public string Driver2Name { get; set; }

        [DisplayName("Příjmení druhého řidiče")]
        public string Driver2Surname { get; set; }

        [DisplayName("Telefon druhého řidiče")]
        public string Driver2Phone { get; set; }

        [DisplayName("Adresa druhého řidiče")]
        public string Driver2Address { get; set; }

        [DisplayName("Č. Řidičského průkazu druhého řidiče")]
        public string Driver2DrivingLicenceId { get; set; }

        [DisplayName("Pojišťovna druhého řidiče")]
        public string Driver2InsuranceCompany { get; set; }

        [DisplayName("Název automobilu druhého řidiče")]
        public string Driver2CarName { get; set; }

        [DisplayName("Barva automobilu druhého řidiče")]
        public string Driver2CarColor { get; set; }

        [DisplayName("SPZ automobilu druhého řidiče")]
        public string Driver2SPZ { get; set; }

        [DisplayName("VIN kód druhého řidiče")]
        public string Driver2VIN { get; set; }

        [DisplayName("Fotka celé situace")]
        public string ImgSituation { get; set; }

        [DisplayName("Detailní fotka vaše vozidla")]
        public string Driver1DetailImg { get; set; }

        [DisplayName("Detailní fotka druhého vozidla")]
        public string Driver2DetailImg { get; set; }

        [DisplayName("Fotka VIN kódu vašeho vozidla")]
        public string Driver1VINImg { get; set; }

        [DisplayName("Fotka VIN kódu druhého řidiče")]
        public string Driver2VINImg { get; set; }

        [DisplayName("Poznámky")]
        [DataType(DataType.MultilineText)]
        public string Info { get; set; }

        [DisplayName("Schopné jízdy")]
        public bool DriveAble { get; set; }

        public int DriveId { get; set; }

        public virtual Drives Drives { get; set; }
    }
}

knihaJizd/Models/Cars.cs
namespace knihaJizd.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class Cars
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cars()
        {
            Drives = new HashSet<Drives>();
        }

        public int Id { get; set; }

        [Required]
        [DisplayName("Název")]
        public string Name { get; set; }

        [Required]
        [DisplayName("VIN Kód")]
        public string VIN { get; set; }

        [Required]
        [DisplayName("Státní poznávaci značka")]
        public string SPZ { get; set; }

        [DisplayName("Barva")]
        public string Color { get; set; }

        [DisplayName("Fotka")]
        public string Photo { get; set; }
        public bool Active { get; set; }
        [DisplayName("Jízdy schopné")]
        public bool DriveAble { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Drives> Drives { get; set; }
    }
}

knihaJizd/Controllers/AccidentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using knihaJizd.Models;

namespace knihaJizd.Controllers
{
    public class AccidentsController : Controller
    {
        private ModelUserDriveCarAcident db = new ModelUserDriveCarAcident();
        

        // GET: Accidents/Create
        public ActionResult Create(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Accidents accidents = db.Accidents.Create();
            accidents.DriveId = (int) id;
            accidents.AccidentTime = DateTime.Now;
            return View(accidents);
        }

        // POST: Accidents/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,AccidentAddress,Driver2Name,Driver2Surname,Driver2Phone,Driver2Address,Driver2DrivingLicenceId,Driver2InsuranceCompany,Driver2CarName,Driver2CarColor,Driver2SPZ,Driver2VIN,ImgSituation,Driver1DetailImg,Driver2DetailImg,Driver1VINImg,Driver2VINImg,Info,DriveAble,DriveId")] Accidents accidents)
        {
            if (ModelState.IsValid)
            {
                if (!accidents.DriveAble)
                {
                    var drive = db.Drives.Find(accidents.DriveId);
                    drive.StopDate = DateTime.Now;
                    drive.StopKm = drive.StartKm;

                    var car = db.Cars.Find(drive.Car);

                    car.DriveAble = false;

                    db.Entry(car).State = EntityState.Modified;
                    db.Entry(drive).State = EntityState.Modified;
                    db.SaveChanges();
                }


                db.Accidents.Add(accidents);
                db.SaveChanges();
                return RedirectToAction("../Cars");
            }

            return View(accidents);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

knihaJizd/Controllers/AdministrationController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using knihaJizd.Models;
using Microsoft.AspNet.Identity;

namespace knihaJizd.Controllers
{
    public class AdministrationController : Controller
    {
        private ModelUserDriveCarAcident db = new ModelUserDriveCarAcident();

        private bool isAdministrator()
        {
            return db.AspNetUsers.Find(User.Identity.GetUserId()).Admin;
        }

        // GET: Accidents list
        public ActionResult Accidents()
        {
            if (!isAdministrator())
            {
                return RedirectToAction("Error", "Administration");
            }
            var returnVal = db.Accidents.ToList();

            if(returnVal.Count != 0)
            {
                returnVal.Reverse();
            }

            return View(returnVal);
        }

        // GET: Accidents/Details/5
        public ActionResult AccidentsDetails(int? id)
        {
            if (!isAdministrator())
            {
                return RedirectToAction("Error", "Administration");
            }

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Accidents accidents = db.Accidents.Find(id);
            if (accidents == null)
            {
                return HttpNotFound();
            }
            return View(accidents);
        }




        // GET: Cars list
        public ActionResult Cars()
        {
            if (!isAdministrator())
            {
                return RedirectToAction("Error", "Administration");
            }

            var cars = db.Cars.Where(c => c.Active == true);

            return View(cars.ToList());
        }

        // GET: Cars/Create
        public ActionResult CarsCreate()
        {
            if (!isAdministrator())
            {
                return RedirectToAction("Error", "Administration");
            }

            return View();
        }

        // POST: Cars/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CarsCreate([Bind(Include = "Id,Name,VIN,SPZ,Color,Photo")] Cars cars)
        {
            if (!isAdministrator())
            {
                return RedirectToAction("Error", "Administration");
            }

            cars.Active = true;

            if (ModelState.IsValid)
            {
                cars.DriveAble = true;
                db.Cars.Add(cars);
                db.SaveChanges();
                return RedirectToAction("Cars");
            }

            return View(cars);
        }

        // GET: Cars/Edit/5
        public ActionResult CarsEdit(int? id)
        {
            if (!isAdministrator())
            {
                return RedirectToAction("Error", "Administration");
            }

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cars cars = db.Cars.Find(id);
            if (cars == null)
            {
                return HttpNotFound();
            }
            return View(cars);
        }

        // POST: Cars/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CarsEdit([Bind(Include = "Id,Name,VIN,SPZ,Color,Photo,DriveAble")] Cars cars)
        {
            if (!isAdministrator())
            {
                return RedirectToAction("Error", "Administration");
            }
            cars.Active = true;
            if (ModelState.IsValid)
            {
                db.Entry(cars).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Cars");
            }
            return View(cars);
        }

        // GET: Cars/Delete/5
        public ActionResult CarsDelete(int? id)
        {
            if (!isAdministrator())
            {
                return RedirectToAction("Error", "Administration");
            }

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cars cars = db.Cars.Find(id);
            if (cars == null)
            {
                return HttpNotFound();
            }
            return View(cars);
        }

        // POST: Cars/Delete/5
        [HttpPost, ActionName("CarsDelete")]
        [ValidateAntiForgeryToken]
        public ActionResult CarsDeleteConfirmed(int id)
        {
            if (id == null)
            {
                return View("Cars");
            }

            if (!isAdministrator())
            {
                return RedirectToAction("Error", "Administration");
            }

            Cars cars = db.Cars.Find(id);
            if (cars == null)
            {
                return HttpNotFound();
            }

            cars.Active = false;
            db.Entry(cars).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Cars");
        }





        // GET: Drives list
        public ActionResult Drives()
        {
            if (!isAdministrator())
            {
                return RedirectToAction("Error", "Administration");
            }

            return View(db.Drives.OrderByDescending(d => d.StartDate).ToList());
        }

        // GET: Users list
        public ActionResult Users()
        {
            if (!isAdministrator())
            {
                return RedirectToAction("Error", "Administration");
            }

            var users = db.AspNetUsers.Where(u => u.Active == true);

            return View(users.ToList());
        }

        // GET: Users Detail
        public ActionResult UsersDetail(string id)
        {
            if(id == "")
            {
                return RedirectToAction("Users", "Administration");
            }

            if (!isAdministrator())
            {
                return RedirectToAction("Error", "Administration");
            }

            var users = db.AspNetUsers.Find(id);

            if (users == null)
            {
                return HttpNotFound();
            }

            return View(users);
        }

        // GET: Users Edit
        public ActionResult UsersEdit(string id)
        {
            if (id == "")
            {
                return RedirectToAction("Users", "Administration");
            }

            if (!isAdministrator())
            {
                return RedirectToAction("Error", "Administration");
            }
            var users = db.AspNetUsers.Find(id);

            users.Active = true;

            if (users == null)
            {
                return HttpNotFound();
            }

            return View(users);
        }

        // POST: User/Edit
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UsersEdit([Bind(Include = "Id,Name,Surname,Address,Email,PhoneNumber,DrivingLicenceId, Admin")] IndexViewModel model, string id)
        {
            if (id == "")
            {
                return RedirectToAction("Users", "Administration");
            }

            if (!isAdministrator())
            {
                return RedirectToAction("Error", "Administration");
            }

            if (ModelState.IsValid)
            {
                AspNetUsers user = db.AspNetUsers.Find(id);
                user.Name = model.Name;
                user.Surname = model.Surname;
                user.Address = model.Address;
                user.Email = model.Email;
                user.PhoneNumber = model.PhoneNumber;
                user.DrivingLicenceId = model.DrivingLicenceId;

                db.Entry(user).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Users");
            }
            return View(model);
        }

        // GET: Users/Delete/5
        public ActionResult UsersDelete(string id)
        {
            if (id == "")
            {
                return RedirectToAction("Users", "Administration");
            }

            if (!isAdministrator())
            {
                return RedirectToAction("Error", "Administration");
            }

            AspNetUsers user = db.AspNetUsers.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("UsersDelete")]
        [ValidateAntiForgeryToken]
        public ActionResult UsersDeleteConfirmed(string id)
        {
            
            if (id == "")
            {
                return View("Users");
            }

            if (!isAdministrator())
            {
                return RedirectToAction("Error", "Administration");
            }

            AspNetUsers user = db.AspNetUsers.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }

            user.Active = false;
            db.Entry(user).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Users");
        }





        // GET: Index
        public ActionResult Index()
        {
            if (!isAdministrator())
            {

knihaJizd/Controllers/CarsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using knihaJizd.Models;
using Microsoft.AspNet.Identity;

namespace knihaJizd.Controllers
{
    public class CarsController : Controller
    {
        private ModelUserDriveCarAcident db = new ModelUserDriveCarAcident();

        // GET: Cars
        public ActionResult Index()
        {
            
            var actualCarQuery = from d in db.Drives
                                  where d.StopKm == 0 || d.StopKm == null
                                  select d.User;

            if (actualCarQuery.Contains(User.Identity.GetUserId()))
            {
                return RedirectToAction("Index", "Drives");
            }


            var innerquery = from c in db.Cars
                             join d in db.Drives on c.Id equals d.Car into ps
                             from r in ps.DefaultIfEmpty()
                             where r.StopKm == 0 || r.StopKm == null
                             select c.Id;

            var innerquery2 = from d in db.Drives
                              select d.Car;

            var query = from c in db.Cars
                        where (!innerquery.Contains(c.Id) || !innerquery2.Contains(c.Id)) && c.Active == true && c.DriveAble == true
                        select c;

            return View(query);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

knihaJizd/Views/Administration/Accidents.cshtml
@model IEnumerable<knihaJizd.Models.Accidents>

@{
    ViewBag.Title = "Nehody";
}

<h1>@ViewBag.Title</h1>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Drives.Cars.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Drives.Cars.SPZ)
        </th>
        <th>
            Jmeno uživatele
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AccidentAddress)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Drives.Cars.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Drives.Cars.SPZ)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Drives.AspNetUsers.Name) @Html.DisplayFor(modelItem => item.Drives.AspNetUsers.Surname)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.AccidentAddress)
        </td>
        <td>
            @Html.ActionLink("Detail", "AccidentsDetails", new { id=item.Id }, new { @class="btn btn-primary btn-xs" })
        </td>
    </tr>
}

</table>

knihaJizd/Views/Administration/AccidentsDetails.cshtml
@model knihaJizd.Models.Accidents

@{
    ViewBag.Title = "Detail nehody";
}

<h1>@ViewBag.Title</h1>

<div>

    <div>

        <!-- Nav tabs -->
        <ul class="nav nav-tabs" role="tablist">
            <li role="presentation" class="active"><a href="#mainData" aria-controls="home" role="tab" data-toggle="tab">Obecné informace o nehodě</a></li>
            <li role="presentation"><a href="#driver1" aria-controls="profile" role="tab" data-toggle="tab">Řidič vašeho vozidla</a></li>
            <li role="presentation"><a href="#driver2" aria-controls="profile" role="tab" data-toggle="tab">Řidič druhého vozida</a></li>
            <li role="presentation"><a href="#driver1foto" aria-controls="home" role="tab" data-toggle="tab">Fotky vašeho vozidla</a></li>
            <li role="presentation"><a href="#driver2foto" aria-controls="home" role="tab" data-toggle="tab">Fotky druhého vozidla</a></li>
        </ul>

        <!-- Tab panes -->
        <div class="tab-content">
            <div role="tabpanel" class="tab-pane active" id="mainData">
                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => model.AccidentAddress)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.AccidentAddress)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.ImgSituation)
                    </dt>

                    <dd>
                        <img src="@Html.DisplayFor(model => model.ImgSituation)" alt="" />
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Info)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Info)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.DriveAble)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.DriveAble)
                    </dd>
                </dl>
            </div>
            <div role="tabpanel" class="tab-pane" id="driver1">
                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => model.Drives.AspNetUsers.Name)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Drives.AspNetUsers.Name)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Drives.AspNetUsers.Surname)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Drives.AspNetUsers.Surname)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Drives.AspNetUsers.PhoneNumber)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Drives.AspNetUsers.PhoneNumber)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Drives.AspNetUsers.Address)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Drives.AspNetUsers.Address)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Drives.AspNetUsers.DrivingLicenceId)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Drives.AspNetUsers.DrivingLicenceId)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Drives.Cars.Name)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Drives.Cars.Name)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Drives.Cars.Color)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Drives.Cars.Color)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Drives.Cars.SPZ)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Drives.Cars.SPZ)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Drives.Cars.VIN)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Drives.Cars.VIN)
                    </dd>
                </dl>
            </div>
            <div role="tabpanel" class="tab-pane" id="driver2">
                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => model.Driver2Name)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Driver2Name)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Driver2Surname)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Driver2Surname)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Driver2Phone)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Driver2Phone)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Driver2Address)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Driver2Address)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Driver2DrivingLicenceId)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Driver2DrivingLicenceId)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Driver2InsuranceCompany)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Driver2InsuranceCompany)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Driver2CarName)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Driver2CarName)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Driver2CarColor)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Driver2CarColor)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Driver2SPZ)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Driver2SPZ)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Driver2VIN)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Driver2VIN)
                    </dd>
                </dl>
            </div>
            <div role="tabpanel" class="tab-pane" id="driver1foto">
                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => model.Driver1DetailImg)
                    </dt>

                    <dd>
                        <img src="@Html.DisplayFor(model => model.Driver1DetailImg)" alt="" />
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Driver1VINImg)
                    </dt>

                    <dd>
                        <img src="@Html.DisplayFor(model => model.Driver1VINImg)" alt="" />
                    </dd>

                    
                </dl>
            </div>
            <div role="tabpanel" class="tab-pane" id="driver2foto">
                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => model.Driver2DetailImg)
                    </dt>

                    <dd>
                        <img src="@Html.DisplayFor(model => model.Driver2DetailImg)" alt="" />
                    </dd>
                    <dt>
                        @Html.DisplayNameFor(model => model.Driver2VINImg)
                    </dt>

                    <dd>
                        <img src="@Html.DisplayFor(model => model.Driver2VINImg)" alt="" />
                    </dd>
                </dl>
            </div>
        </div>
    </div>
         
</div>

knihaJizd/Views/Administration/Cars.cshtml
@model IEnumerable<knihaJizd.Models.Cars>

@{
    ViewBag.Title = "Automobily";
}
<div class="clearfix">
    <h1 class="pull-left">@ViewBag.Title</h1>
    <div class="pull-right">
        @Html.ActionLink("Přidat automobil", "CarsCreate", null, new { @class="btn btn-success" })
    </div>
</div>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Photo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.VIN)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SPZ)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Color)
        </th>
        <th></th>
    </tr>


@foreach (var item in Model)
{
    <tr @(item.DriveAble ? String.Empty : "class=bg-danger" )>
        <td>
            <img src="@Html.DisplayFor(modelItem => item.Photo)" alt="">
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.VIN)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SPZ)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Color)
        </td>
        <td class="text-right">
            @Html.ActionLink("Smazat", "CarsDelete", new { id = item.Id }, new { @class = "btn btn-danger btn-xs" })
            @Html.ActionLink("Upravit", "CarsEdit", new { id = item.Id }, new { @class = "btn btn-primary btn-xs" })
        </td>
    </tr>
        
}

</table>

knihaJizd/Views/Administration/CarsDelete.cshtml
@model knihaJizd.Models.Cars

@{
    ViewBag.Title = "Smazat automobil";
}

<h1>@ViewBag.Title</h1>
<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VIN)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VIN)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SPZ)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SPZ)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Color)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Color)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Photo)
        </dt>
        <dd>
            <img src="@Html.DisplayFor(model => model.Photo)" alt="">
        </dd>
        
    </dl>

    <h3 class="text-danger">Opravdu chcete smazat?</h3>
    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color text-right">
            <input type="submit" value="Smazat" class="btn btn-danger" />
        </div>
    }
</div>

knihaJizd/Views/Administration/Index.cshtml
@model IEnumerable<knihaJizd.Models.Accidents>

@{
    ViewBag.Title = "Administrace";
}

<h1>Vítej v administraci</h1>

<div class="row">
    <div class="col-sm-3">
        @Html.ActionLink("Auta", "Cars", null, new { @class = "btn btn-success btn-lg btn-block" })
    </div>
    <div class="col-sm-3">
        @Html.ActionLink("Uživatelé", "Users", null, new { @class = "btn btn-success btn-lg btn-block" })
    </div>
    <div class="col-sm-3">
        @Html.ActionLink("Jízdy", "Drives", null, new { @class = "btn btn-success btn-lg btn-block" })
    </div>
    <div class="col-sm-3">
        @Html.ActionLink("Nehody", "Accidents", null, new { @class = "btn btn-success btn-lg btn-block" })
    </div>
</div>